### ISSUE TITLE
Code not working for FDE.py

### ISSUE THREAD

**Issue by ymiao8** [rbassett3/FDE-Tools#1]
Hey,
I tried to run the example (had tried all the examples  which showed the same error) but it seems like the code in FDE.py is not working and here's the screenshot for the error. I am a little bit confused. Thank you so much! 
![image](https://user-images.githubusercontent.com/77041248/129516411-4accf3a8-f4e9-457d-b116-20419c9ac5d9.png)

**Comment by ymiao8** [comment]
@rbassett3

**Comment by rbassett3** [comment]
@ymiao8. Thank you for the mention--I didn't see your initial comment.

This codebase was written some years ago, and I made the unfortunate decision then to use Python 2.7. This cause of this error is that you are using Python 3 instead.

Here's the details of a conda environment named "fde" that I just spun together to get it working. It uses outdated packages compatible with my original code. Copy this content to a file called fde.yml. Then run `conda env create -f fde.yml`. There may be some issues if you're not running linux, but I hope they're minor. At the very least, you should be able to get by with installing the important packages according to their version numbers (numpy, matplotlib, scikit-learn, osqp, and the all-important Python 2.7). I hope this helps.

```
name: fde
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - backports_abc=0.5=py_1
  - blas=1.0=openblas
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.5.30=ha878542_0
  - certifi=2019.11.28=py27h8c360ce_1
  - cmake=3.5.0=3
  - cycler=0.10.0=py_2
  - dbus=1.13.6=hfdff14a_1
  - expat=2.4.1=h9c3ff4c_0
  - fontconfig=2.13.0=hd36ec8e_5
  - freetype=2.8.1=hfa320df_1
  - functools32=3.2.3.2=py_3
  - futures=3.3.0=py27h8c360ce_1
  - gettext=0.19.8.1=hf34092f_1004
  - glib=2.66.3=h58526e2_0
  - gst-plugins-base=1.12.5=hde13a9d_0
  - gstreamer=1.12.4=hb53b477_0
  - icu=58.2=hf484d3e_1000
  - jpeg=9d=h36c2ea0_0
  - kiwisolver=1.1.0=py27h9e3301b_1
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=8_openblas
  - libcblas=3.9.0=8_openblas
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=11.1.0=hc902ee8_8
  - libgfortran-ng=7.5.0=h14aa051_19
  - libgfortran4=7.5.0=h14aa051_19
  - libglib=2.66.3=hbe7bbb4_0
  - libgomp=11.1.0=hc902ee8_8
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=8_openblas
  - libopenblas=0.3.12=pthreads_hb3c22a3_1
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.1.0=h56837e0_8
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.9=h13577e0_2
  - lz4-c=1.9.2=heb0550a_3
  - matplotlib=2.0.2=py27h334a7c2_1
  - ncurses=6.2=h58526e2_4
  - numpy=1.16.1=py27h99e49ec_1
  - numpy-base=1.16.1=py27h2f8d375_1
  - openssl=1.0.2u=h516909a_0
  - pcre=8.45=h9c3ff4c_0
  - pip=20.1.1=pyh9f0ad1d_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.6.0=py27h13b7fb3_1008
  - python=2.7.18=h02575d3_0
  - python-dateutil=2.8.1=py_0
  - python_abi=2.7=1_cp27mu
  - pytz=2020.1=pyh9f0ad1d_0
  - qt=5.6.2=hd25b39d_14
  - readline=8.1=h46c0cb4_0
  - scikit-learn=0.20.3=py27ha8026db_1
  - scipy=1.2.1=py27h921218d_2
  - setuptools=44.0.0=py27_0
  - singledispatch=3.6.1=pyh44b312d_0
  - sip=4.18.1=py27hf484d3e_1000
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h9cd32fc_0
  - subprocess32=3.5.4=py27h516909a_0
  - tk=8.6.10=h21135ba_1
  - tornado=5.1.1=py27h14c3975_1000
  - wheel=0.37.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - future==0.18.2
    - osqp==0.2.1
prefix: /home/robert/.conda/envs/fde
```

**Comment by ymiao8** [comment]
> @ymiao8. Thank you for the mention--I didn't see your initial comment.
> 
> This codebase was written some years ago, and I made the unfortunate decision then to use Python 2.7. This cause of this error is that you are using Python 3 instead.
> 
> Here's the details of a conda environment named "fde" that I just spun together to get it working. It uses outdated packages compatible with my original code. Copy this content to a file called fde.yml. Then run `conda env create -f fde.yml`. There may be some issues if you're not running linux, but I hope they're minor. At the very least, you should be able to get by with installing the important packages according to their version numbers (numpy, matplotlib, scikit-learn, osqp, and the all-important Python 2.7). I hope this helps.
> 
> ```
> name: fde
> channels:
>   - anaconda
>   - conda-forge
>   - defaults
> dependencies:
>   - _libgcc_mutex=0.1=conda_forge
>   - _openmp_mutex=4.5=1_gnu
>   - backports=1.0=py_2
>   - backports.functools_lru_cache=1.6.1=py_0
>   - backports_abc=0.5=py_1
>   - blas=1.0=openblas
>   - bzip2=1.0.8=h7b6447c_0
>   - ca-certificates=2021.5.30=ha878542_0
>   - certifi=2019.11.28=py27h8c360ce_1
>   - cmake=3.5.0=3
>   - cycler=0.10.0=py_2
>   - dbus=1.13.6=hfdff14a_1
>   - expat=2.4.1=h9c3ff4c_0
>   - fontconfig=2.13.0=hd36ec8e_5
>   - freetype=2.8.1=hfa320df_1
>   - functools32=3.2.3.2=py_3
>   - futures=3.3.0=py27h8c360ce_1
>   - gettext=0.19.8.1=hf34092f_1004
>   - glib=2.66.3=h58526e2_0
>   - gst-plugins-base=1.12.5=hde13a9d_0
>   - gstreamer=1.12.4=hb53b477_0
>   - icu=58.2=hf484d3e_1000
>   - jpeg=9d=h36c2ea0_0
>   - kiwisolver=1.1.0=py27h9e3301b_1
>   - ld_impl_linux-64=2.36.1=hea4e1c9_2
>   - libblas=3.9.0=8_openblas
>   - libcblas=3.9.0=8_openblas
>   - libedit=3.1.20191231=h14c3975_1
>   - libffi=3.2.1=he1b5a44_1007
>   - libgcc-ng=11.1.0=hc902ee8_8
>   - libgfortran-ng=7.5.0=h14aa051_19
>   - libgfortran4=7.5.0=h14aa051_19
>   - libglib=2.66.3=hbe7bbb4_0
>   - libgomp=11.1.0=hc902ee8_8
>   - libiconv=1.16=h516909a_0
>   - liblapack=3.9.0=8_openblas
>   - libopenblas=0.3.12=pthreads_hb3c22a3_1
>   - libpng=1.6.37=h21135ba_2
>   - libstdcxx-ng=11.1.0=h56837e0_8
>   - libuuid=2.32.1=h7f98852_1000
>   - libuv=1.40.0=h7b6447c_0
>   - libxcb=1.13=h7f98852_1003
>   - libxml2=2.9.9=h13577e0_2
>   - lz4-c=1.9.2=heb0550a_3
>   - matplotlib=2.0.2=py27h334a7c2_1
>   - ncurses=6.2=h58526e2_4
>   - numpy=1.16.1=py27h99e49ec_1
>   - numpy-base=1.16.1=py27h2f8d375_1
>   - openssl=1.0.2u=h516909a_0
>   - pcre=8.45=h9c3ff4c_0
>   - pip=20.1.1=pyh9f0ad1d_0
>   - pthread-stubs=0.4=h36c2ea0_1001
>   - pyparsing=2.4.7=pyh9f0ad1d_0
>   - pyqt=5.6.0=py27h13b7fb3_1008
>   - python=2.7.18=h02575d3_0
>   - python-dateutil=2.8.1=py_0
>   - python_abi=2.7=1_cp27mu
>   - pytz=2020.1=pyh9f0ad1d_0
>   - qt=5.6.2=hd25b39d_14
>   - readline=8.1=h46c0cb4_0
>   - scikit-learn=0.20.3=py27ha8026db_1
>   - scipy=1.2.1=py27h921218d_2
>   - setuptools=44.0.0=py27_0
>   - singledispatch=3.6.1=pyh44b312d_0
>   - sip=4.18.1=py27hf484d3e_1000
>   - six=1.16.0=pyh6c4a22f_0
>   - sqlite=3.36.0=h9cd32fc_0
>   - subprocess32=3.5.4=py27h516909a_0
>   - tk=8.6.10=h21135ba_1
>   - tornado=5.1.1=py27h14c3975_1000
>   - wheel=0.37.0=pyhd8ed1ab_1
>   - xorg-libxau=1.0.9=h7f98852_0
>   - xorg-libxdmcp=1.1.3=h7f98852_0
>   - xz=5.2.5=h516909a_1
>   - zlib=1.2.11=h516909a_1010
>   - zstd=1.4.5=h9ceee32_0
>   - pip:
>     - future==0.18.2
>     - osqp==0.2.1
> prefix: /home/robert/.conda/envs/fde
> ```

Thank you so much for clarifying my issue! It is working with the environment you provided. 
Best,
Yu
